@echo off
COLOR B0
TITLE REVERSES THE ili FILES IN VIPER RACING TRACKS
ECHO.
ECHO.
ECHO THIS FILE REVERSES THE RACE DIRECTION OF A VIPER RACING TRACK
ECHO BY CHANGING THE ili FILES GENERATED BY SUCAHYOS VR-TRACKMAKER PROGRAM
ECHO.
ECHO.
IF EXIST oldilifiles ( GOTO EXISTS ) ELSE ( GOTO NOTHERE )

:EXISTS
echo FOLDER EXISTS - PLEASE RENAME OR DELETE IT FIRST
echo JUST IN CASE OVERWRITING IT CAUSES THINGS
echo TO GO PEAR SHAPED !!
goto END


:END
pause
exit
:NOTHERE
md oldilifiles
copy track.ili oldilifiles
copy track-reverse.ili oldilifiles
copy track-ai.ili oldilifiles
copy track-ai-reverse.ili oldilifiles
ECHO.
ECHO ORIGINAL FILES WERE SUCCESSFULLY BACKED UP IN THE oldilifiles FOLDER
ECHO.
rename track-reverse.ili track-reverse.bak.ili 
rename track.ili track.bak.ili
rename track-reverse.bak.ili track.ili 
rename track.bak.ili track-reverse.ili
rename track-ai.ili track-ai.bak.ili  
rename track-ai-reverse.ili track-ai-reverse.bak.ili
rename track-ai.bak.ili track-ai-reverse.ili 
rename track-ai-reverse.bak.ili track-ai.ili
PING 1.1.1.1 -n 1 -w 500 >NUL
ECHO BACKUP AND RENAMING OPERATION COMPLETE
ECHO.
ECHO.
ECHO THE VIPER RACING TRACK CAN NOW BE PUT TOGETHER
ECHO AND THE RACING DIRECTION WILL BE REVERSED 
ECHO.
ECHO.
pause
exit /b